---
  - name: get mysql password
    shell : |
      until [ ! -z $mysql_password ] 
      do 
        mysql_password=`docker logs mysql1 2>&1 | grep PASSWORD | awk '{print $5}'`
      done
      docker logs mysql1 2>&1 | grep PASSWORD | awk '{print $5}'
    register: mysql_password
  - debug: var=mysql_password.stdout

  - name: create test mysql Databases
    shell : sleep 30 ; docker exec -i mysql1 mysql -uroot -p'{{ mysql_password.stdout }}' -e 'CREATE DATABASE IF NOT EXISTS '{{ item.name }}''
    with_items: "{{ DBLIST }}"
    #loop: "{{ DBLIST }}" 
    when: item.name != ""
    register: output
  - debug: var=output.stdout_lines
